management.endpoints.web.exposure.include: health,info
server.port: 5000
spring:
  kafka:
    bootstrap-servers: "b-1.among-eus-events.ytwrun.c2.kafka.us-east-2.amazonaws.com:9092,b-2.among-eus-events.ytwrun.c2.kafka.us-east-2.amazonaws.com:9092"
    consumer:
      group-id: consumer-group-tasks
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.zuehlke.amongeus.tasks
        spring.json.value.default.type: com.zuehlke.amongeus.tasks.model.GameStartEvent
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer